//===----------------------------------------------------------------------===//
//
// This source file is part of the Swift.org open source project
//
// Copyright (c) 2014 - 2026 Apple Inc. and the Swift project authors
// Licensed under Apache License v2.0 with Runtime Library Exception
//
// See https://swift.org/LICENSE.txt for license information
// See https://swift.org/CONTRIBUTORS.txt for the list of Swift project authors
//
//===----------------------------------------------------------------------===//

import Foundation

/// A version number that can be specified in the configuration file, which allows us to change the
/// format in the future if desired and still support older files.
///
/// Note that *adding* new configuration values is not a version-breaking change; swift-format will
/// use default values when loading older configurations that don't contain the new settings. This
/// value only needs to be updated if the configuration changes in a way that would be incompatible
/// with the previous format.
internal let highestSupportedConfigurationVersion = 1

/// Holds the complete set of configured values and defaults.
public struct Configuration: Codable, Equatable {

  private enum CodingKeys: CodingKey {
    case version
    case maximumBlankLines
    case lineLength
    case spacesBeforeEndOfLineComments
    case tabWidth
    case indentation
    case respectsExistingLineBreaks
    case lineBreakBeforeControlFlowKeywords
    case lineBreakBeforeEachArgument
    case lineBreakBeforeEachGenericRequirement
    case lineBreakBetweenDeclarationAttributes
    case lineBreakBeforeEachChainComponent
    case attachLoneDeclarationAttributes
    case prioritizeKeepingFunctionOutputTogether
    case indentConditionalCompilationBlocks
    case lineBreakAroundMultilineExpressionChainComponents
    case fileScopedDeclarationPrivacy
    case indentSwitchCaseLabels
    case rules
    case spacesAroundRangeFormationOperators
    case noAssignmentInExpressions
    case multilineTrailingCommaBehavior
    case multiElementCollectionTrailingCommas
    case collectionElementLayout
    case magicTrailingComma
    case forceBrokenArgumentsInMultilineArrayLiterals
    case forceBrokenClosureBodies
    case forceBrokenCodeBlockBodies
    case reflowMultilineStringLiterals
    case indentBlankLines
    case orderedImports
    case swiftTestingNamingConventions
    case blankLinePolicy
    case iterateToFixpoint
  }

  /// A dictionary containing the default enabled/disabled states of rules, keyed by the rules'
  /// names.
  ///
  /// This value is generated by `generate-swift-format` based on the `isOptIn` value of each rule.
  public static let defaultRuleEnablements: [String: Bool] = RuleRegistry.rules

  /// The version of this configuration.
  private var version: Int = highestSupportedConfigurationVersion

  /// MARK: Common configuration

  /// The dictionary containing the rule names that we wish to run on. A rule is not used if it is
  /// marked as `false`, or if it is missing from the dictionary.
  public var rules: [String: Bool]

  /// The maximum number of consecutive blank lines that may appear in a file.
  public var maximumBlankLines: Int

  /// The maximum length of a line of source code, after which the formatter will break lines.
  public var lineLength: Int

  /// Number of spaces that precede line comments.
  public var spacesBeforeEndOfLineComments: Int

  /// The width of the horizontal tab in spaces.
  ///
  /// This value is used when converting indentation types (for example, from tabs into spaces).
  public var tabWidth: Int

  /// A value representing a single level of indentation.
  ///
  /// All indentation will be conducted in multiples of this configuration.
  public var indentation: Indent

  /// Indicates that the formatter should try to respect users' discretionary line breaks when
  /// possible.
  ///
  /// For example, a short `if` statement and its single-statement body might be able to fit on one
  /// line, but for readability the user might break it inside the curly braces. If this setting is
  /// true, those line breaks will be kept. If this setting is false, the formatter will act more
  /// "opinionated" and collapse the statement onto a single line.
  public var respectsExistingLineBreaks: Bool

  /// MARK: Rule-specific configuration

  /// Determines the line-breaking behavior for control flow keywords that follow a closing brace,
  /// like `else` and `catch`.
  ///
  /// If true, a line break will be added before the keyword, forcing it onto its own line. If
  /// false (the default), the keyword will be placed after the closing brace (separated by a
  /// space).
  public var lineBreakBeforeControlFlowKeywords: Bool

  /// Determines the line-breaking behavior for generic arguments and function arguments when a
  /// declaration is wrapped onto multiple lines.
  ///
  /// If false (the default), arguments will be laid out horizontally first, with line breaks only
  /// being fired when the line length would be exceeded. If true, a line break will be added before
  /// each argument, forcing the entire argument list to be laid out vertically.
  public var lineBreakBeforeEachArgument: Bool

  /// Determines the line-breaking behavior for generic requirements when the requirements list
  /// is wrapped onto multiple lines.
  ///
  /// If true, a line break will be added before each requirement, forcing the entire requirements
  /// list to be laid out vertically. If false (the default), requirements will be laid out
  /// horizontally first, with line breaks only being fired when the line length would be exceeded.
  public var lineBreakBeforeEachGenericRequirement: Bool

  /// If true, a line break will be added between adjacent attributes.
  public var lineBreakBetweenDeclarationAttributes: Bool

  /// Determines the line-breaking behavior for the components of a call chain — a chain
  /// containing a function call or subscript, such as `Text(…).font(…).padding(…)` in SwiftUI
  /// code.
  ///
  /// If true, a line break is added before every chain component that follows a call, even when
  /// the whole chain would fit on one line. Components not preceded by a call are unaffected.
  /// If false (the default), chain components are laid out horizontally first, with line breaks
  /// fired only when the line length is exceeded.
  public var lineBreakBeforeEachChainComponent: Bool

  /// Determines whether a lone declaration attribute shares its declaration's line instead of
  /// being placed on its own line, refining `lineBreakBetweenDeclarationAttributes`.
  ///
  /// When enabled, two or more attributes still go one per line, but a single attribute stays
  /// attached to its declaration, breaking only when the line length requires it. It has no
  /// effect unless attributes are separated one per line; for macro declarations that separation
  /// is keyed to `lineBreakBeforeEachArgument` instead.
  public var attachLoneDeclarationAttributes: Bool

  /// Determines if function-like declaration outputs should be prioritized to be together with the
  /// function signature's right (closing) parenthesis.
  ///
  /// If false (the default), function output (i.e. throws, return type) is not prioritized to be
  /// together with the signature's right parenthesis, and when the line length would be exceeded,
  /// a line break will be fired after the function signature first, indenting the declaration output
  /// one additional level. If true, a line break will be fired further up in the function's
  /// declaration (e.g. generic parameters, parameters) before breaking on the function's output.
  public var prioritizeKeepingFunctionOutputTogether: Bool

  /// Determines the indentation behavior for `#if`, `#elseif`, and `#else`.
  public var indentConditionalCompilationBlocks: Bool

  /// Determines whether line breaks should be forced before and after multiline components of
  /// dot-chained expressions, such as function calls and subscripts chained together through member
  /// access (i.e. "." expressions). When any component is multiline and this option is true, a line
  /// break is forced before the "." of the component and after the component's closing delimiter
  /// (i.e. right paren, right bracket, right brace, etc.).
  public var lineBreakAroundMultilineExpressionChainComponents: Bool

  /// Determines the formal access level (i.e., the level specified in source code) for file-scoped
  /// declarations whose effective access level is private to the containing file.
  public var fileScopedDeclarationPrivacy: FileScopedDeclarationPrivacyConfiguration

  /// Determines if `case` statements should be indented compared to the containing `switch` block.
  ///
  /// When `false`, the correct form is:
  /// ```swift
  /// switch someValue {
  /// case someCase:
  ///   someStatement
  /// ...
  /// }
  /// ```
  ///
  /// When `true`, the correct form is:
  /// ```swift
  /// switch someValue {
  ///   case someCase:
  ///     someStatement
  ///   ...
  /// }
  ///```
  public var indentSwitchCaseLabels: Bool

  /// Determines whether whitespace should be forced before and after the range formation operators
  /// `...` and `..<`.
  public var spacesAroundRangeFormationOperators: Bool

  /// Contains exceptions for the `NoAssignmentInExpressions` rule.
  public var noAssignmentInExpressions: NoAssignmentInExpressionsConfiguration

  /// Determines how trailing commas in comma-separated lists should be handled during formatting.
  public enum MultilineTrailingCommaBehavior: String, Codable {
    case alwaysUsed
    case neverUsed
    case keptAsWritten
  }

  /// Determines how trailing commas in multiline comma-separated lists are handled during formatting.
  ///
  /// This setting takes precedence over `multiElementCollectionTrailingCommas`.
  /// If set to `.keptAsWritten` (the default), the formatter defers to `multiElementCollectionTrailingCommas`
  /// for collections only. In all other cases, existing trailing commas are preserved as-is and not modified.
  /// If set to `.alwaysUsed` or `.neverUsed`, that behavior is applied uniformly across all list types,
  /// regardless of `multiElementCollectionTrailingCommas`.
  public var multilineTrailingCommaBehavior: MultilineTrailingCommaBehavior

  /// Determines if multi-element collection literals should have trailing commas.
  ///
  /// When `true` (default), the correct form is:
  /// ```swift
  /// let MyCollection = [1, 2]
  /// ...
  /// let MyCollection = [
  ///   "a": 1,
  ///   "b": 2,
  /// ]
  /// ```
  ///
  /// When `false`, the correct form is:
  /// ```swift
  /// let MyCollection = [1, 2]
  /// ...
  /// let MyCollection = [
  ///   "a": 1,
  ///   "b": 2
  /// ]
  /// ```
  public var multiElementCollectionTrailingCommas: Bool

  /// Determines how elements of collection literals are laid out when the literal spans multiple
  /// lines.
  public enum CollectionElementLayout: String, Codable, CaseIterable {
    /// Broken collection literals may pack multiple elements per line, filling each line up to
    /// the line length.
    case binPack

    /// Broken collection literals place each element on its own line.
    case onePerLine

    /// Like `onePerLine`, except collection literals whose elements are all short simple scalar
    /// literals (numbers — including a single leading sign — booleans, `nil`, single-line string
    /// literals, and bare enum cases, each at most 10 bytes wide and not preceded by a comment)
    /// are packed multiple elements per line. For dictionary literals, each key and each value
    /// must independently satisfy those constraints.
    case fillShortLiterals
  }

  /// Determines how elements of collection literals (arrays and dictionaries) are laid out when
  /// the literal spans multiple lines. See `CollectionElementLayout` for the available layouts.
  public var collectionElementLayout: CollectionElementLayout

  /// Determines whether a trailing comma after the last element of a collection literal, function
  /// call argument list, or function/enum-case/closure parameter list forces the list to break
  /// one element per line, even when the list would fit on a single line.
  ///
  /// This matches Black's "magic trailing comma" behavior. The comma is honored only when the
  /// list fits on the line where it starts — otherwise it cannot be distinguished from a comma
  /// the formatter added itself — and a comma that forced the layout is preserved even when
  /// trailing commas would otherwise be removed. Exceptions:
  ///
  /// - A trailing comma on the sole compactly arranged argument of a call never forces the
  ///   vertical layout; the comma is then handled like any single-element trailing comma.
  /// - A single-element trailing comma is never added, and is kept whenever `magicTrailingComma`
  ///   is enabled; otherwise it is removed, except where `multilineTrailingCommaBehavior`
  ///   leaves trailing commas as written.
  /// - A list containing comments has its fits test computed from the group's conservative
  ///   width, because a comment's width depends on the layout around it.
  public var magicTrailingComma: Bool

  /// Determines whether the argument lists of function-call elements in an array literal are
  /// broken one argument per line when the array literal spans multiple lines.
  ///
  /// Verticality propagates inward from the literal's actual emitted layout (including manual
  /// breaks when author line breaks are preserved), so the decision is stable across formatting
  /// passes. Only calls with at least two arguments are affected; a single-argument call cannot
  /// be partially wrapped, so breaking it open adds no determinism.
  public var forceBrokenArgumentsInMultilineArrayLiterals: Bool

  /// Determines whether closures containing at least one statement are always laid out vertically
  /// — each statement on its own line, with the closing brace on its own line — even when the
  /// entire closure would fit on a single line.
  ///
  /// This applies to every closure regardless of context, including nested single-statement
  /// closures. Empty closures and closures with no statements are unaffected. The default behavior
  /// already breaks open closures with multiple statements; this option extends that behavior to
  /// single-statement closures.
  public var forceBrokenClosureBodies: Bool

  /// Determines whether code blocks — the brace-delimited statement bodies of declarations and
  /// control-flow statements, explicit accessor bodies (e.g. `get { … }`), and switch case
  /// statement lists — are always laid out vertically, even when the entire body would fit on a
  /// single line.
  ///
  /// With this option enabled, `if x { y() }` and `func f() { bar() }` are each broken onto
  /// three lines. Empty bodies are unaffected, and a single-statement body containing a closure
  /// composes with `forceBrokenClosureBodies`. Type member blocks and implicit single-expression
  /// accessors (e.g. `var h: Int { 5 }`) are not code blocks and are out of scope.
  public var forceBrokenCodeBlockBodies: Bool

  /// Determines how multiline string literals should reflow when formatted.
  public enum MultilineStringReflowBehavior: String, Codable {
    /// Never reflow multiline string literals.
    case never
    /// Reflow lines in string literal that exceed the maximum line length. For example with a line length of 10:
    /// ```swift
    /// """
    /// an escape\
    ///  line break
    /// a hard line break
    /// """
    /// ```
    /// will be formatted as:
    /// ```swift
    /// """
    /// an escape\
    ///  line break
    /// a hard \
    /// line break
    /// """
    /// ```
    /// The existing `\` is left in place, but the line over line length is broken.
    case onlyLinesOverLength
    /// Always reflow multiline string literals, this will ignore existing escaped newlines in the literal and reflow each line. Hard linebreaks are still respected.
    /// For example, with a line length of 10:
    /// ```swift
    /// """
    /// one \
    /// word \
    /// a line.
    /// this is too long.
    /// """
    /// ```
    /// will be formatted as:
    /// ```swift
    /// """
    /// one word \
    /// a line.
    /// this is \
    /// too long.
    /// """
    /// ```
    case always

    var isNever: Bool {
      self == .never
    }

    var isAlways: Bool {
      self == .always
    }
  }

  /// A private enum created to maintain backward compatibility with swift-format version 601.0.0,
  /// which had a `MultilineStringReflowBehavior` enum without a String raw type.
  ///
  /// In version 601.0.0, the `reflowMultilineStringLiterals` configuration was encoded as an object
  /// with a single key (e.g., `{ "never": {} }`) rather than as a string (e.g., `"never"`). This
  /// enum allows decoding from both formats:
  /// - First, we attempt to decode as a String using `MultilineStringReflowBehavior`
  /// - If that fails, we fall back to this legacy format
  /// - If both attempts fail, an error will be thrown
  ///
  /// This approach preserves compatibility without requiring a configuration version bump.
  private enum LegacyMultilineStringReflowBehavior: Codable {
    case never
    case onlyLinesOverLength
    case always

    /// Converts this legacy enum to the corresponding `MultilineStringReflowBehavior` value.
    func toMultilineStringReflowBehavior() -> MultilineStringReflowBehavior {
      switch self {
      case .never: .never
      case .always: .always
      case .onlyLinesOverLength: .onlyLinesOverLength
      }
    }
  }

  @_spi(Internal) public static let swiftFormatFilename = ".swift-format"

  public var reflowMultilineStringLiterals: MultilineStringReflowBehavior

  /// Determines whether to add indentation whitespace to blank lines or remove it entirely.
  ///
  /// If true, blank lines will be modified to match the current indentation level:
  /// if they contain whitespace, the existing whitespace will be adjusted, and if they are empty, spaces will be added to match the indentation.
  /// If false (the default), the whitespace in blank lines will be removed entirely.
  public var indentBlankLines: Bool

  /// Configuration for the `OrderedImports` rule.
  public var orderedImports: OrderedImportsConfiguration

  /// Configuration for the `SwiftTestingNamingConventions` rule.
  public var swiftTestingNamingConventions: SwiftTestingNamingConventionsConfiguration

  /// Configuration for the `BlankLinePolicy` rule, which governs where blank lines are required,
  /// forbidden, or left to the author's discretion.
  public var blankLinePolicy: BlankLinePolicyConfiguration

  /// Determines whether formatting iterates until the output stops changing.
  ///
  /// Rule interactions can occasionally produce output that changes again when formatted a second
  /// time. When this setting is true, the formatter repeats the entire format pass — rules and
  /// pretty printing — until the output is a fixed point, and throws an error if it fails to
  /// converge within a bounded number of passes instead of silently returning unstable output.
  /// Line and offset selections are excluded because their ranges are not valid for the
  /// formatted text of later passes, and the syntax-tree-based format entry point always
  /// performs a single pass. When false (the default), exactly one pass is performed, matching
  /// the formatter's existing single-pass behavior.
  public var iterateToFixpoint: Bool

  /// Creates a new `Configuration` by loading it from a configuration file.
  public init(contentsOf url: URL) throws {
    let data = try Data(contentsOf: url)
    try self.init(data: data)
  }

  /// Creates a new `Configuration` by decoding it from the UTF-8 representation in the given data.
  public init(data: Data) throws {
    let jsonDecoder = JSONDecoder()
    #if canImport(Darwin) || compiler(>=6)
    jsonDecoder.allowsJSON5 = true
    #endif
    self = try jsonDecoder.decode(Configuration.self, from: data)
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)

    // If the version number is not present, assume it is 1.
    self.version = try container.decodeIfPresent(Int.self, forKey: .version) ?? 1
    guard version <= highestSupportedConfigurationVersion else {
      throw SwiftFormatError.unsupportedConfigurationVersion(
        version,
        highestSupported: highestSupportedConfigurationVersion
      )
    }

    // If we ever introduce a new version, this is where we should switch on the decoded version
    // number and dispatch to different decoding methods.

    // Unfortunately, to allow the user to leave out configuration options in the JSON, we would
    // have to make them optional properties, but that makes using the type in the rest of the code
    // more annoying because we'd have to unwrap everything. So, we override this initializer and
    // provide the defaults ourselves if needed. We get those defaults by pulling them from a
    // default-initialized instance.
    let defaults = Configuration()

    self.maximumBlankLines =
      try container.decodeIfPresent(Int.self, forKey: .maximumBlankLines)
      ?? defaults.maximumBlankLines
    self.lineLength =
      try container.decodeIfPresent(Int.self, forKey: .lineLength)
      ?? defaults.lineLength
    self.spacesBeforeEndOfLineComments =
      try container.decodeIfPresent(Int.self, forKey: .spacesBeforeEndOfLineComments)
      ?? defaults.spacesBeforeEndOfLineComments
    self.tabWidth =
      try container.decodeIfPresent(Int.self, forKey: .tabWidth)
      ?? defaults.tabWidth
    // Nonsense geometry would otherwise trap deep inside the pretty printer; reject it at the
    // configuration boundary with an actionable error instead.
    guard self.lineLength > 0 else {
      throw DecodingError.dataCorrupted(
        .init(
          codingPath: container.codingPath + [CodingKeys.lineLength],
          debugDescription: "'lineLength' must be a positive integer."
        )
      )
    }
    guard self.tabWidth > 0 else {
      throw DecodingError.dataCorrupted(
        .init(
          codingPath: container.codingPath + [CodingKeys.tabWidth],
          debugDescription: "'tabWidth' must be a positive integer."
        )
      )
    }
    self.indentation =
      try container.decodeIfPresent(Indent.self, forKey: .indentation)
      ?? defaults.indentation
    self.respectsExistingLineBreaks =
      try container.decodeIfPresent(Bool.self, forKey: .respectsExistingLineBreaks)
      ?? defaults.respectsExistingLineBreaks
    self.lineBreakBeforeControlFlowKeywords =
      try container.decodeIfPresent(Bool.self, forKey: .lineBreakBeforeControlFlowKeywords)
      ?? defaults.lineBreakBeforeControlFlowKeywords
    self.lineBreakBeforeEachArgument =
      try container.decodeIfPresent(Bool.self, forKey: .lineBreakBeforeEachArgument)
      ?? defaults.lineBreakBeforeEachArgument
    self.lineBreakBeforeEachGenericRequirement =
      try container.decodeIfPresent(Bool.self, forKey: .lineBreakBeforeEachGenericRequirement)
      ?? defaults.lineBreakBeforeEachGenericRequirement
    self.lineBreakBetweenDeclarationAttributes =
      try container.decodeIfPresent(Bool.self, forKey: .lineBreakBetweenDeclarationAttributes)
      ?? defaults.lineBreakBetweenDeclarationAttributes
    self.lineBreakBeforeEachChainComponent =
      try container.decodeIfPresent(Bool.self, forKey: .lineBreakBeforeEachChainComponent)
      ?? defaults.lineBreakBeforeEachChainComponent
    self.attachLoneDeclarationAttributes =
      try container.decodeIfPresent(Bool.self, forKey: .attachLoneDeclarationAttributes)
      ?? defaults.attachLoneDeclarationAttributes
    self.prioritizeKeepingFunctionOutputTogether =
      try container.decodeIfPresent(Bool.self, forKey: .prioritizeKeepingFunctionOutputTogether)
      ?? defaults.prioritizeKeepingFunctionOutputTogether
    self.indentConditionalCompilationBlocks =
      try container.decodeIfPresent(Bool.self, forKey: .indentConditionalCompilationBlocks)
      ?? defaults.indentConditionalCompilationBlocks
    self.lineBreakAroundMultilineExpressionChainComponents =
      try container.decodeIfPresent(
        Bool.self,
        forKey: .lineBreakAroundMultilineExpressionChainComponents
      )
      ?? defaults.lineBreakAroundMultilineExpressionChainComponents
    self.spacesAroundRangeFormationOperators =
      try container.decodeIfPresent(
        Bool.self,
        forKey: .spacesAroundRangeFormationOperators
      )
      ?? defaults.spacesAroundRangeFormationOperators
    self.fileScopedDeclarationPrivacy =
      try container.decodeIfPresent(
        FileScopedDeclarationPrivacyConfiguration.self,
        forKey: .fileScopedDeclarationPrivacy
      )
      ?? defaults.fileScopedDeclarationPrivacy
    self.indentSwitchCaseLabels =
      try container.decodeIfPresent(Bool.self, forKey: .indentSwitchCaseLabels)
      ?? defaults.indentSwitchCaseLabels
    self.noAssignmentInExpressions =
      try container.decodeIfPresent(
        NoAssignmentInExpressionsConfiguration.self,
        forKey: .noAssignmentInExpressions
      )
      ?? defaults.noAssignmentInExpressions
    self.multilineTrailingCommaBehavior =
      try container.decodeIfPresent(MultilineTrailingCommaBehavior.self, forKey: .multilineTrailingCommaBehavior)
      ?? defaults.multilineTrailingCommaBehavior
    self.multiElementCollectionTrailingCommas =
      try container.decodeIfPresent(
        Bool.self,
        forKey: .multiElementCollectionTrailingCommas
      )
      ?? defaults.multiElementCollectionTrailingCommas
    self.collectionElementLayout =
      try container.decodeIfPresent(CollectionElementLayout.self, forKey: .collectionElementLayout)
      ?? defaults.collectionElementLayout
    self.magicTrailingComma =
      try container.decodeIfPresent(Bool.self, forKey: .magicTrailingComma)
      ?? defaults.magicTrailingComma
    self.forceBrokenArgumentsInMultilineArrayLiterals =
      try container.decodeIfPresent(
        Bool.self,
        forKey: .forceBrokenArgumentsInMultilineArrayLiterals
      )
      ?? defaults.forceBrokenArgumentsInMultilineArrayLiterals
    self.forceBrokenClosureBodies =
      try container.decodeIfPresent(Bool.self, forKey: .forceBrokenClosureBodies)
      ?? defaults.forceBrokenClosureBodies
    self.forceBrokenCodeBlockBodies =
      try container.decodeIfPresent(Bool.self, forKey: .forceBrokenCodeBlockBodies)
      ?? defaults.forceBrokenCodeBlockBodies

    self.reflowMultilineStringLiterals = try {
      // Try to decode `reflowMultilineStringLiterals` as a string
      // This handles configurations using the String raw value format (e.g. "never").
      // If an error occurs, we'll silently bypass it and fall back to the legacy behavior.
      if let behavior = try? container.decodeIfPresent(
        MultilineStringReflowBehavior.self,
        forKey: .reflowMultilineStringLiterals
      ) {
        return behavior
      }

      // If the modern format fails, try to decode as an object with a single key.
      // This handles configurations from swift-format v601.0.0 (e.g. { "never": {} }).
      // If an error occurs in this step, we'll propagate it to the caller.
      if let legacyBehavior = try container.decodeIfPresent(
        LegacyMultilineStringReflowBehavior.self,
        forKey: .reflowMultilineStringLiterals
      ) {
        return legacyBehavior.toMultilineStringReflowBehavior()
      }

      // If the key is not present in the configuration at all, use the default value.
      return defaults.reflowMultilineStringLiterals
    }()

    self.indentBlankLines =
      try container.decodeIfPresent(
        Bool.self,
        forKey: .indentBlankLines
      )
      ?? defaults.indentBlankLines

    self.orderedImports =
      try container.decodeIfPresent(
        OrderedImportsConfiguration.self,
        forKey: .orderedImports
      )
      ?? defaults.orderedImports

    self.swiftTestingNamingConventions =
      try container.decodeIfPresent(
        SwiftTestingNamingConventionsConfiguration.self,
        forKey: .swiftTestingNamingConventions
      )
      ?? defaults.swiftTestingNamingConventions

    self.blankLinePolicy =
      try container.decodeIfPresent(
        BlankLinePolicyConfiguration.self,
        forKey: .blankLinePolicy
      )
      ?? defaults.blankLinePolicy

    self.iterateToFixpoint =
      try container.decodeIfPresent(Bool.self, forKey: .iterateToFixpoint)
      ?? defaults.iterateToFixpoint

    // If the `rules` key is not present at all, default it to the built-in set
    // so that the behavior is the same as if the configuration had been
    // default-initialized. To get an empty rules dictionary, one can explicitly
    // set the `rules` key to `{}`.
    self.rules =
      try container.decodeIfPresent([String: Bool].self, forKey: .rules)
      ?? defaults.rules
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)

    try container.encode(version, forKey: .version)
    try container.encode(maximumBlankLines, forKey: .maximumBlankLines)
    try container.encode(lineLength, forKey: .lineLength)
    try container.encode(spacesBeforeEndOfLineComments, forKey: .spacesBeforeEndOfLineComments)
    try container.encode(tabWidth, forKey: .tabWidth)
    try container.encode(indentation, forKey: .indentation)
    try container.encode(respectsExistingLineBreaks, forKey: .respectsExistingLineBreaks)
    try container.encode(lineBreakBeforeControlFlowKeywords, forKey: .lineBreakBeforeControlFlowKeywords)
    try container.encode(lineBreakBeforeEachArgument, forKey: .lineBreakBeforeEachArgument)
    try container.encode(lineBreakBeforeEachGenericRequirement, forKey: .lineBreakBeforeEachGenericRequirement)
    try container.encode(prioritizeKeepingFunctionOutputTogether, forKey: .prioritizeKeepingFunctionOutputTogether)
    try container.encode(indentConditionalCompilationBlocks, forKey: .indentConditionalCompilationBlocks)
    try container.encode(lineBreakBetweenDeclarationAttributes, forKey: .lineBreakBetweenDeclarationAttributes)
    try container.encode(lineBreakBeforeEachChainComponent, forKey: .lineBreakBeforeEachChainComponent)
    try container.encode(attachLoneDeclarationAttributes, forKey: .attachLoneDeclarationAttributes)
    try container.encode(
      lineBreakAroundMultilineExpressionChainComponents,
      forKey: .lineBreakAroundMultilineExpressionChainComponents
    )
    try container.encode(
      spacesAroundRangeFormationOperators,
      forKey: .spacesAroundRangeFormationOperators
    )
    try container.encode(fileScopedDeclarationPrivacy, forKey: .fileScopedDeclarationPrivacy)
    try container.encode(indentSwitchCaseLabels, forKey: .indentSwitchCaseLabels)
    try container.encode(noAssignmentInExpressions, forKey: .noAssignmentInExpressions)
    try container.encode(multiElementCollectionTrailingCommas, forKey: .multiElementCollectionTrailingCommas)
    try container.encode(collectionElementLayout, forKey: .collectionElementLayout)
    try container.encode(magicTrailingComma, forKey: .magicTrailingComma)
    try container.encode(
      forceBrokenArgumentsInMultilineArrayLiterals,
      forKey: .forceBrokenArgumentsInMultilineArrayLiterals
    )
    try container.encode(forceBrokenClosureBodies, forKey: .forceBrokenClosureBodies)
    try container.encode(forceBrokenCodeBlockBodies, forKey: .forceBrokenCodeBlockBodies)
    try container.encode(multilineTrailingCommaBehavior, forKey: .multilineTrailingCommaBehavior)
    try container.encode(reflowMultilineStringLiterals, forKey: .reflowMultilineStringLiterals)
    try container.encode(indentBlankLines, forKey: .indentBlankLines)
    try container.encode(orderedImports, forKey: .orderedImports)
    try container.encode(swiftTestingNamingConventions, forKey: .swiftTestingNamingConventions)
    try container.encode(blankLinePolicy, forKey: .blankLinePolicy)
    try container.encode(iterateToFixpoint, forKey: .iterateToFixpoint)
    try container.encode(rules, forKey: .rules)
  }

  /// Returns the URL of the configuration file that applies to the given file or directory.
  public static func url(forConfigurationFileApplyingTo url: URL) -> URL? {
    // Despite the variable's name, this value might start out first as a file path (the path to a
    // source file being formatted). However, it will immediately have its basename removed in the
    // loop below, and from then on serve as a directory path only.
    var candidateDirectory = url.absoluteURL.standardized
    var isDirectory: ObjCBool = false
    if FileManager.default.fileExists(atPath: candidateDirectory.path, isDirectory: &isDirectory),
      isDirectory.boolValue
    {
      // If the path actually was a directory, append a fake basename so that the trimming code
      // below doesn't have to deal with the first-time special case.
      candidateDirectory.appendPathComponent("placeholder")
    }
    repeat {
      candidateDirectory.deleteLastPathComponent()
      let candidateFile = candidateDirectory.appendingPathComponent(Self.swiftFormatFilename)
      if FileManager.default.isReadableFile(atPath: candidateFile.path) {
        return candidateFile
      }
    } while !candidateDirectory.isRoot

    return nil
  }
}

/// Configuration for the `FileScopedDeclarationPrivacy` rule.
public struct FileScopedDeclarationPrivacyConfiguration: Codable, Equatable {
  public enum AccessLevel: String, Codable {
    /// Private file-scoped declarations should be declared `private`.
    ///
    /// If a file-scoped declaration is declared `fileprivate`, it will be diagnosed (in lint mode)
    /// or changed to `private` (in format mode).
    case `private`

    /// Private file-scoped declarations should be declared `fileprivate`.
    ///
    /// If a file-scoped declaration is declared `private`, it will be diagnosed (in lint mode) or
    /// changed to `fileprivate` (in format mode).
    case `fileprivate`
  }

  /// The formal access level to use when encountering a file-scoped declaration with effective
  /// private access.
  public var accessLevel: AccessLevel = .private

  public init() {}
}

/// Configuration for the `NoAssignmentInExpressions` rule.
public struct NoAssignmentInExpressionsConfiguration: Codable, Equatable {
  /// A list of function names where assignments are allowed to be embedded in expressions that are
  /// passed as parameters to that function.
  public var allowedFunctions: [String] = [
    // Allow `XCTAssertNoThrow` because `XCTAssertNoThrow(x = try ...)` is clearer about intent than
    // `x = try XCTUnwrap(try? ...)` or force-unwrapped if you need to use the value `x` later on
    // in the test.
    "XCTAssertNoThrow"
  ]

  public init() {}
}

/// Configuration for the `OrderedImports` rule.
public struct OrderedImportsConfiguration: Codable, Equatable {
  /// Determines whether imports within conditional compilation blocks should be ordered.
  public var includeConditionalImports = false
  /// Determines whether imports are separated into groups based on their type.
  public var shouldGroupImports = true
  public init() {}
}

/// Configuration for the `SwiftTestingNamingConventions` rule.
public struct SwiftTestingNamingConventionsConfiguration: Codable, Equatable {
  /// If true, `@Suite` should not be used if it doesn't specify any arguments; that is, marking a
  /// test type with `@Suite` is unnecessary because any type with `@Test`s is automatically a
  /// suite.
  public var forbidSuiteWithoutParameters = false

  /// If true, `@Suite` should not specify a separate string description.
  public var forbidSuiteDescription = false

  /// If true, `@Test` should not specify a separate string description.
  public var forbidTestDescription = false

  /// If true, `@Test` function names must be raw identifiers (surrounded by backticks).
  public var requireRawIdentifierTestNames = false

  public init() {}
}

/// The primitive policies that can be applied to blank lines at a syntactic boundary.
///
/// Every other policy in `BlankLinePolicyConfiguration` is one of these primitives or a named
/// expansion that picks between them per boundary.
public enum BlankLinePolicyValue: String, Codable, Equatable {
  /// Blank lines are forbidden at this boundary; any that exist will be removed.
  case none
  /// Exactly one blank line is required at this boundary; it will be inserted if missing and any
  /// extra blank lines will be removed.
  case exactlyOne
  /// The author may choose to have zero or one blank line at this boundary; the formatter will
  /// neither insert nor remove one. The global `maximumBlankLines` limit still applies.
  case optional
}

/// The policy for blank lines between the members of a type, extension, or protocol, and
/// between top-level declarations.
public enum DeclarationBlankLinePolicy: String, Codable, Equatable {
  /// An expansion of the primitive values applied per-boundary: exactly one blank line is
  /// required between scope-like declarations (functions, initializers, computed properties,
  /// nested types) and at kind transitions, while list-like declarations of the same kind
  /// (stored properties, enum cases, typealiases, imports) may be grouped with or without blank
  /// lines.
  case scopeSeparated
  /// Blank lines between the declarations are forbidden.
  case none
  /// Exactly one blank line is required between all declarations.
  case exactlyOne
  /// The author chooses where blank lines go.
  case optional
}

/// The policy for blank lines between the cases of a `switch` statement.
public enum SwitchCaseBlankLinePolicy: String, Codable, Equatable {
  /// An expansion of the primitive values applied per-boundary: exactly one blank line is
  /// required between adjacent cases when either case is multiline, and blank lines are
  /// forbidden between adjacent single-line cases.
  case auto
  /// Blank lines between cases are forbidden.
  case none
  /// Exactly one blank line is required between all cases.
  case exactlyOne
  /// The author chooses where blank lines go between cases.
  case optional
}

/// The policy for blank lines around leading `guard` statements in the body of a function,
/// closure, or other braced statement.
public enum GuardPrologueBlankLinePolicy: String, Codable, Equatable {
  /// An expansion of the primitive values: consecutive leading guard statements are kept tight
  /// (no blank lines between them) and exactly one blank line separates the final leading guard
  /// from the rest of the body.
  case separated
  /// Blank lines are forbidden between consecutive leading guard statements and between the
  /// final leading guard and the rest of the body.
  case none
  /// Exactly one blank line is required between consecutive leading guard statements and
  /// between the final leading guard and the rest of the body.
  case exactlyOne
  /// The author chooses where blank lines go around guard statements.
  case optional
}

/// The policy for blank lines around `// MARK:` comments. A MARK comment takes precedence over
/// the policy of the boundary it appears at, except before the first item of a scope, where the
/// scope-edge policy owns the boundary; when the `guardPrologue` policy is not `optional`, the
/// boundary before a MARK at a guard-prologue position belongs to the prologue's policy.
public struct MarkBlankLinePolicy: Codable, Equatable {
  public enum CodingKeys: CodingKey {
    case before
    case after
  }

  /// The policy for blank lines before a `// MARK:` comment.
  public var before: BlankLinePolicyValue = .exactlyOne

  /// The policy for blank lines between a `// MARK:` comment and the declaration or member that
  /// follows it.
  public var after: BlankLinePolicyValue = .none

  public init() {}

  public init(before: BlankLinePolicyValue, after: BlankLinePolicyValue) {
    self.before = before
    self.after = after
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    let defaults = MarkBlankLinePolicy()
    self.before =
      try container.decodeIfPresent(BlankLinePolicyValue.self, forKey: .before) ?? defaults.before
    self.after =
      try container.decodeIfPresent(BlankLinePolicyValue.self, forKey: .after) ?? defaults.after
  }
}

/// Configuration for the `BlankLinePolicy` rule.
///
/// Each axis governs blank lines at one kind of syntactic boundary; most accept the primitive
/// values `none`, `exactlyOne`, and `optional` (see `BlankLinePolicyValue`). Axes that describe
/// gaps rather than separations (`scopeEdges`, `afterCaseLabel`, `attributes`, `expressions`,
/// `conditionalCompilationEdges`, and `beforeElse`) only accept `none` and `optional`: those
/// boundaries sit directly against a delimiter (a brace, a case-label colon, an `#endif`)
/// whose placement is fixed by other layout options, so requiring a blank line there could
/// contradict those decisions. The `statements` axis accepts `none` and `optional` as well:
/// requiring a blank line between every pair of statements would contradict the tight
/// groupings that `guardPrologue` and author-placed blank lines exist to express.
///
/// Blank lines inside multi-line string literals and comments are content and are never
/// modified.
public struct BlankLinePolicyConfiguration: Codable, Equatable {
  public enum CodingKeys: CodingKey {
    case betweenDeclarations
    case scopeEdges
    case members
    case marks
    case switchCases
    case afterCaseLabel
    case attributes
    case expressions
    case conditionalCompilationEdges
    case guardPrologue
    case beforeElse
    case statements
  }

  /// The policy for blank lines between top-level declarations (and between the declarations
  /// inside a top-level conditional compilation block).
  public var betweenDeclarations: DeclarationBlankLinePolicy = .scopeSeparated

  /// The policy for blank lines directly after an opening brace and directly before a closing
  /// brace. Defaults to `optional` so that enabling the overlapping
  /// `NoEmptyLinesOpeningClosingBraces` rule as well does not produce duplicate findings.
  public var scopeEdges: BlankLinePolicyValue = .optional

  /// The policy for blank lines between members of a type, extension, or protocol, including
  /// within `#if` regions.
  public var members: DeclarationBlankLinePolicy = .scopeSeparated

  /// The policy for blank lines around `// MARK:` comments.
  public var marks: MarkBlankLinePolicy = MarkBlankLinePolicy()

  /// The policy for blank lines between the cases of a `switch` statement.
  public var switchCases: SwitchCaseBlankLinePolicy = .auto

  /// The policy for blank lines between a `case` label and its first statement.
  public var afterCaseLabel: BlankLinePolicyValue = .none

  /// The policy for blank lines between adjacent attributes and between an attribute list and
  /// the declaration it annotates.
  public var attributes: BlankLinePolicyValue = .none

  /// The policy for blank lines between the elements of multiline argument lists (including
  /// tuples) and collection literals.
  public var expressions: BlankLinePolicyValue = .none

  /// The policy for blank lines directly after a `#if`/`#elseif`/`#else` directive and directly
  /// before `#endif`.
  public var conditionalCompilationEdges: BlankLinePolicyValue = .none

  /// The policy for blank lines around leading `guard` statements in the body of a function,
  /// closure, or other braced statement.
  public var guardPrologue: GuardPrologueBlankLinePolicy = .separated

  /// The policy for blank lines between `}` and a following `else` or `catch` keyword.
  public var beforeElse: BlankLinePolicyValue = .none

  /// The policy for blank lines between the statements of a code-block body (function bodies,
  /// closure bodies, branch and loop bodies, switch case bodies, and getter bodies). With the
  /// default of `optional` the author's blank lines are preserved, clamped by
  /// `maximumBlankLines`.
  public var statements: BlankLinePolicyValue = .optional

  public init() {}

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    let defaults = BlankLinePolicyConfiguration()
    self.betweenDeclarations =
      try container.decodeIfPresent(DeclarationBlankLinePolicy.self, forKey: .betweenDeclarations)
      ?? defaults.betweenDeclarations
    self.scopeEdges =
      try container.decodeIfPresent(BlankLinePolicyValue.self, forKey: .scopeEdges)
      ?? defaults.scopeEdges
    self.members =
      try container.decodeIfPresent(DeclarationBlankLinePolicy.self, forKey: .members)
      ?? defaults.members
    self.marks =
      try container.decodeIfPresent(MarkBlankLinePolicy.self, forKey: .marks) ?? defaults.marks
    self.switchCases =
      try container.decodeIfPresent(SwitchCaseBlankLinePolicy.self, forKey: .switchCases)
      ?? defaults.switchCases
    self.afterCaseLabel =
      try container.decodeIfPresent(BlankLinePolicyValue.self, forKey: .afterCaseLabel)
      ?? defaults.afterCaseLabel
    self.attributes =
      try container.decodeIfPresent(BlankLinePolicyValue.self, forKey: .attributes)
      ?? defaults.attributes
    self.expressions =
      try container.decodeIfPresent(BlankLinePolicyValue.self, forKey: .expressions)
      ?? defaults.expressions
    self.conditionalCompilationEdges =
      try container.decodeIfPresent(BlankLinePolicyValue.self, forKey: .conditionalCompilationEdges)
      ?? defaults.conditionalCompilationEdges
    self.guardPrologue =
      try container.decodeIfPresent(GuardPrologueBlankLinePolicy.self, forKey: .guardPrologue)
      ?? defaults.guardPrologue
    self.beforeElse =
      try container.decodeIfPresent(BlankLinePolicyValue.self, forKey: .beforeElse)
      ?? defaults.beforeElse
    self.statements =
      try container.decodeIfPresent(BlankLinePolicyValue.self, forKey: .statements)
      ?? defaults.statements

    // Axes that describe gaps rather than separations cannot meaningfully require a blank line.
    let gapAxes: [(key: CodingKeys, value: BlankLinePolicyValue)] = [
      (.scopeEdges, scopeEdges),
      (.afterCaseLabel, afterCaseLabel),
      (.attributes, attributes),
      (.expressions, expressions),
      (.conditionalCompilationEdges, conditionalCompilationEdges),
      (.beforeElse, beforeElse),
      (.statements, statements),
    ]
    for (key, value) in gapAxes where value == .exactlyOne {
      throw DecodingError.dataCorrupted(
        .init(
          codingPath: container.codingPath + [key],
          debugDescription:
            "'\(key.stringValue)' cannot be 'exactlyOne'; it accepts 'none' or 'optional'."
        )
      )
    }
  }
}
